version: "3"

services:
    web:
        container_name: web
        build:
            context: .
            args:
                - GITHUB_TOKEN=${GITHUB_TOKEN}
        image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${TAG}
        links:
            - database
            - redis
        expose:
            - 80
            - 443
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app:delegated
        environment:
          VIRTUAL_HOST: "127.0.0.1:80"
          REDIS_PORT: 6379
          APP_USER_LOCAL: "true"
          MAIL_USERNAME: ""
          MAIL_PASSWORD: ""

    database:
        container_name: database
        image: digitonic1/mysql8:latest
        environment:
            MYSQL_ROOT_PASSWORD: arc
            MYSQL_DATABASE: arc
            MYSQL_USER: arc
            MYSQL_PASSWORD: arc
        expose:
            - 3306
            - 4306
        ports:
            - "4306:3306"

    redis:
        container_name: redis
        image: redis:latest
        expose:
            - 6379
        ports:
            - "6379:6379"

